description: ND subtractions from US taxable income.
values:
  2021-01-01:
    - us_govt_interest
    - nd_ltcg_subtraction  # long-term capital gains
    - nd_qdiv_subtraction  # qualified dividends
    - taxable_social_security

metadata:
  unit: variable
  label: ND subtractions from US taxable income
  reference:
  - title: 2021 ND income tax form
    href: https://www.tax.nd.gov/sites/www/files/documents/forms/form-nd-1-2021.pdf
  - title: 2021 ND income tax instructions
    href: https://www.tax.nd.gov/sites/www/files/documents/forms/2021-individual-income-tax-booklet.pdf
  - title: 2022 ND income tax form
    href: https://www.tax.nd.gov/sites/www/files/documents/forms/form-nd-1-2022.pdf
  - title: 2022 ND income tax instructions
    href: https://www.tax.nd.gov/sites/www/files/documents/forms/2022-individual-income-tax-booklet.pdf
